<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="10421" started-at="2022-02-07T15:27:54 IST" finished-at="2022-02-07T15:28:04 IST">
    <groups>
    </groups>
    <test name="Surefire test" duration-ms="10421" started-at="2022-02-07T15:27:54 IST" finished-at="2022-02-07T15:28:04 IST">
      <class name="DeleteMethodTest">
        <test-method status="PASS" signature="getUserData()[pri:0, instance:DeleteMethodTest@6321e813]" name="getUserData" is-config="true" duration-ms="4341" started-at="2022-02-07T15:27:54 IST" finished-at="2022-02-07T15:27:58 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUserData -->
        <test-method status="PASS" signature="deleteBook()[pri:0, instance:DeleteMethodTest@6321e813]" name="deleteBook" duration-ms="1016" started-at="2022-02-07T15:27:58 IST" finished-at="2022-02-07T15:27:59 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteBook -->
        <test-method status="PASS" signature="getUserData()[pri:0, instance:DeleteMethodTest@6321e813]" name="getUserData" is-config="true" duration-ms="1011" started-at="2022-02-07T15:28:03 IST" finished-at="2022-02-07T15:28:04 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUserData -->
      </class> <!-- DeleteMethodTest -->
      <class name="SimpleGetTest">
        <test-method status="PASS" signature="GetWeatherDetails()[pri:0, instance:SimpleGetTest@72b6cbcc]" name="GetWeatherDetails" duration-ms="2106" started-at="2022-02-07T15:28:01 IST" finished-at="2022-02-07T15:28:03 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GetWeatherDetails -->
      </class> <!-- SimpleGetTest -->
      <class name="PutMethodTest">
        <test-method status="FAIL" signature="UpdateRecords()[pri:0, instance:PutMethodTest@6737fd8f]" name="UpdateRecords" duration-ms="1856" started-at="2022-02-07T15:27:59 IST" finished-at="2022-02-07T15:28:01 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [429]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1240)
at org.testng.Assert.assertEquals(Assert.java:1274)
at PutMethodTest.UpdateRecords(PutMethodTest.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UpdateRecords -->
      </class> <!-- PutMethodTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
